# Generated by Django 3.1.5 on 2021-01-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klubok', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('Парк', 'Парк'), ('Ресторан', 'Ресторан'), ('Кафе', 'Кафе'), ('Кинотеатр', 'Кинотеатр'), ('ТРЦ', 'Торговый центр'), ('Улица', 'Улица'), ('Сквер', 'Сквер'), ('Достопримечательность', 'Достопримечательность')], default='Park', max_length=255),
        ),
    ]
